# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://scanner-warranty-bali-take.trycloudflare.com"
client_id = "769d7b3b0d233f22f819e8a9f853c1be"
embedded = true
handle = "consumer-app-4"
name = "consumer-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://scanner-warranty-bali-take.trycloudflare.com/auth/callback",
  "https://scanner-warranty-bali-take.trycloudflare.com/auth/shopify/callback",
  "https://scanner-warranty-bali-take.trycloudflare.com/api/auth/callback",
  "https://scanner-warranty-bali-take.trycloudflare.com/auth/instagram/callback",
  "https://scanner-warranty-bali-take.trycloudflare.com/api/fetchPosts"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7fb02b5e.myshopify.com"
include_config_on_deploy = true
